// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1) {
  return window['go']['main']['App']['AddRule'](arg1);
}

export function CheckNow(arg1) {
  return window['go']['main']['App']['CheckNow'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function GetRule(arg1) {
  return window['go']['main']['App']['GetRule'](arg1);
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function StartMonitoring(arg1) {
  return window['go']['main']['App']['StartMonitoring'](arg1);
}

export function StopMonitoring(arg1) {
  return window['go']['main']['App']['StopMonitoring'](arg1);
}

export function UpdateRule(arg1) {
  return window['go']['main']['App']['UpdateRule'](arg1);
}
