// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddRule(arg1:models.MonitorRule):Promise<void>;

export function CheckNow(arg1:string):Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function GetRule(arg1:string):Promise<models.MonitorRule>;

export function GetRules():Promise<Array<models.MonitorRule>>;

export function StartMonitoring(arg1:string):Promise<void>;

export function StopMonitoring(arg1:string):Promise<void>;

export function UpdateRule(arg1:models.MonitorRule):Promise<void>;
